# Generated by Django 6.0.3 on 2026-04-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_user_id',
            field=models.UUIDField(db_default=models.Func(function='uuidv7'), editable=False, unique=True),
        ),
    ]
